@url=http://localhost:8080/api/v1
post {{url}}/products/
Content-Type: application/json

{
    "product_type": "smartphone",
    "name": "Galaxy S22",
    "thumb": "https://example.com/images/galaxy_s22.jpg",
    "description": "The latest Samsung Galaxy S22 with cutting-edge features.",
    "price": 999.99,
    "brand": "Samsung",
    "size": 6.1,
    "os": "Android 12",
    "ram": 8,
    "rom": 128,
    "pin": 3700,
    "cpu": "Exynos 2200",
    "gpu": "Mali-G78 MP14",
    "x_size": 70.6,
    "y_size": 146.0,
    "panel_type": "Dynamic AMOLED 2X",
    "resolution": "2400 x 1080"
}